USE [master]
GO

/****** Object:  Database [CITY_JAIL]    Script Date: 2/7/2023 10:32:35 PM ******/
CREATE DATABASE [CITY_JAIL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CITY_JAIL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CITY_JAIL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CITY_JAIL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CITY_JAIL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CITY_JAIL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CITY_JAIL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CITY_JAIL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CITY_JAIL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CITY_JAIL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CITY_JAIL] SET ARITHABORT OFF 
GO

ALTER DATABASE [CITY_JAIL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CITY_JAIL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CITY_JAIL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CITY_JAIL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CITY_JAIL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CITY_JAIL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CITY_JAIL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CITY_JAIL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CITY_JAIL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CITY_JAIL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CITY_JAIL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CITY_JAIL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CITY_JAIL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CITY_JAIL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CITY_JAIL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CITY_JAIL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CITY_JAIL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CITY_JAIL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CITY_JAIL] SET  MULTI_USER 
GO

ALTER DATABASE [CITY_JAIL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CITY_JAIL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CITY_JAIL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CITY_JAIL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CITY_JAIL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CITY_JAIL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CITY_JAIL] SET  READ_WRITE 
GO

